### ISSUE TITLE
Add support for unindent via shift+tab

### ISSUE THREAD

**Issue by fregante** [fregante/indent-textarea#1]
Currently shift+tab is ignored and its default behavior moves the focus to the previous input.

**Comment by vladimyr** [comment]
Could you please add support for <kbd>cmd</kbd> + <kbd>[</kbd> and <kbd>cmd</kbd> + <kbd>]</kbd> too?

**Comment by mqliutie** [comment]
Do you have any good ideas to achieve this purpose?

**Comment by fregante** [comment]
I’ve already implemented it here, but I haven’t finished it https://github.com/bfred-it/indent-textarea/pull/6

**Comment by mqliutie** [comment]
I hope this library has this feature, waiting for good news.

**Comment by fregante** [comment]
Added in #6 🎉 but only available as a prerelease for now.

```sh
npm install indent-textarea@2.0.0-0
```
