### ISSUE TITLE
Change event from `keydown` to `keypress`

### ISSUE THREAD

**Issue by fregante** [fregante/indent-textarea#18]
I think it's the correct event, but needs testing.

**Comment by avivmu** [comment]
[Keypress is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event) so stick with keydown

**Comment by fregante** [comment]
Interesting, thanks. I wonder why I didn’t suggest `input`. 🤔 Possibly because tab doesn’t cause an input but just changes focus
