### ISSUE TITLE
Add option to indent with spaces instead of tabs

### ISSUE THREAD

**Issue by leafac** [fregante/indent-textarea#21]
As far as I understand, indent-textarea hardcodes the indentation to be tabs (see `\t` in https://github.com/fregante/indent-textarea/blob/dc47aeb512b9b3a72006c1f3ba4fd7efb46f084a/index.ts). I believe it’d be nice to the option to use spaces instead. At least in my use case, tabs looked too wide.

---

On an unrelated note that may not warrant its own issue: on the README there are examples with the following lines:

```javascript
document.querySelector('textarea').addEventListener('click', eventHandler);
```

```javascript
delegate(document.body, 'textarea', 'input', eventHandler);
```

But wouldn’t it make more sense to listen for the `keydown` event, like [the `.watch()` method does](https://github.com/fregante/indent-textarea/blob/dc47aeb512b9b3a72006c1f3ba4fd7efb46f084a/index.ts#L124)?

**Comment by fregante** [comment]
Refer to https://github.com/fregante/indent-textarea/issues/8

> At least in my use case, tabs looked too wide

I suggest using `tab-size` https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size

```css
:root {
	tab-size: 2;
}
```

> But wouldn’t it make more sense to listen for the `keydown` event, like [the `.watch()` method does](https://github.com/fregante/indent-textarea/blob/dc47aeb512b9b3a72006c1f3ba4fd7efb46f084a/index.ts#L124)?

Thank you! Updated: https://github.com/fregante/indent-textarea/commit/d5ac267a4916fc2382ec33a217f06ca4f91c26f7

I had probably carried those examples over from my other module https://github.com/fregante/text-field-edit

**Comment by fregante** [comment]
> But wouldn’t it make more sense to listen for the `keydown` event, like [the `.watch()` method does](https://github.com/fregante/indent-textarea/blob/dc47aeb512b9b3a72006c1f3ba4fd7efb46f084a/index.ts#L124)?

Thank you! Updated: https://github.com/fregante/indent-textarea/commit/d5ac267a4916fc2382ec33a217f06ca4f91c26f7

I had probably carried those examples over from my other module https://github.com/fregante/text-field-edit

**Comment by leafac** [comment]
> Refer to #8

Oops, I looked for a related issue before opening this one but it seems like missed it! 😅

> No because while editors might provide some help treating each indentation as a single piece, textareas don't offer that, so using 4 spaces requires you to press `left` 4 times instead of once, for example.

Hmmm, I’m not sure I understand the issue here, would you mind expanding? As far as I understand editors such as Visual Studio Code & Xcode (these are the editors I use) indent with spaces and require you to “press `left` 4 times.”

> I suggest using `tab-size` https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size

Great point. Thanks!

> I had probably carried those examples over from my other module https://github.com/fregante/text-field-edit

Oh, that makes sense. By the way, text-field-edit is great! Thanks for all your open-source projects!
