### ISSUE TITLE
Demo doesn't work on mac

### ISSUE THREAD

**Issue by dy** [fregante/indent-textarea#28]
Pressing tab changes focus.
https://user-images.githubusercontent.com/300067/222966264-d1d4706b-31c6-4dce-b69a-a44f478de997.mov

**Comment by dy** [comment]
Ok, that's because 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/300067/222966313-12945a3b-971e-4257-81ee-38cac59022d8.png">

**Comment by fregante** [comment]
Thank you so much for opening the issue. I fixed it in 2c8fb91
