### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by smir-ant** [fregante/indent-textarea#30]
same issue like https://github.com/fregante/text-field-edit/issues/33

![image](https://github.com/user-attachments/assets/3de118e8-be19-4e85-8a51-6fbd8191d459)

what about new variant/way instead of the deprecated?
and what the new way..?

cuz i don't know too, but i really want to know simple solution 🤔

**Comment by fregante** [comment]
This is the only way. They deprecated the API but there’s no way to add text to a field while preserving undo/redo.
