### ISSUE TITLE
Add support for unwatch

### ISSUE THREAD

**Issue by anhnhoktvn** [fregante/indent-textarea#7]
Could we return an unwatch function to clear up

**Comment by fregante** [comment]
Version 2 exports `eventHandler` so you can use it as

```js
import {eventHandler} from 'indent-textarea';

textarea.removeEventListener('input', eventHandler);
```

Provably at some point I'll also add a full `.unwatch` method.

**Comment by jsdw** [comment]
I looked for this immediately as well. I noticed the alternate API though so can make do with that.

I'd recommend returning a function from the `watch` method that unwatches. There is precent for that approach, and it works well with eg `useEffect` hooks in things like React.

**Comment by fregante** [comment]
Can you show me that pattern in react? I have it in my other module (delegate-it) and honestly I don’t like it.

**Comment by jsdw** [comment]
Inside a react component you may do something like:

```
useEffect(() => {
  const textarea = r.current
  return indentation.watch(textarea)
},[r.current])
```

Where if the function provided to `useEffect` returns a function, the returned function is run each time the effect needs to be re-run (eg each time the element we're adding your handlers to changes).

see https://reactjs.org/docs/hooks-effect.html - specifically the section "Effects With Cleanup" for more.

I'd also note that Angular (version 1 at least; I'm not uptodate with newer versions) used a similar pattern a fair amount (`$scope.$watch(blah)` returns a function that unwatches, for instance).

Ultimately though it's up to you what API you think feels best - it would be trivial to call a separate function as well if you prefer that :)

**Comment by fregante** [comment]
The reason why I’m not happy about returning a function is that the function has to be created and kept in memory whether you need it or not. 

Your example would be:

```js
useEffect(() => {
  const textarea = r.current
  indentation.watch(textarea)
  return () => indentation.unwatch(textarea)
},[r.current])
```
